name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
  
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.25
        uses: actions/setup-go@v2
        with:
          version: v1.25

      - name: Build Go application
        run: go build -o go-web-app

      - name: Test
        run: go test ./...
      

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{vars.DOCKERHUB_USERNAME}}/go-web-app:${{github.run_id}}
  
  update-tag-into-Helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm chart image tag 
        run: |
          sed -i 's/tag: ".*"/tag: "${{github.run_id}}"/' Helm/go-web-app/values.yaml

      - name: Commit and push changes
        runs: |
          git config --global user.name "Vivek Inturi"
          git config --global user.email ""
          git add Helm/go-web-app/values.yaml
          git commit -m "Update Helm chart image tag to ${{github.run_id}}"
          git push origin main  
    